### ISSUE TITLE
The "font" option does not work well

### ISSUE THREAD

**Issue by Yllelder** [winne27/flot-valuelabels#19]
I have changed the font of the labels using the option "_font_". I use the font "_Roboto_" loaded locally into the CSS (not from Google Fonts), but the labels are only displayed with the correct font from time to time. **When I refresh the page, sometimes it works and sometimes it doesn't**. It is a lottery.

**Correct font:**
![sans-serif](https://imgur.com/djrpUe0.png)

**Incorrect font:**
![serif](https://imgur.com/BRRcMYM.png)

This is my code of the chart:

```javascript
var data = [[1, 8], [2, 8], [3, 8], [4, 9], [5, 9], [6, 9], [7, 10], [8, 10], [9, 9], [10, 6], [11, 2], [12, 4], [13, 2]];

var dataset = [
		{
			data: data,
			lines: {show: true, lineWidth: 3},
			curvedLines: {apply: true, monotonicFit: true}
		},
		{
			data: data,
			points: {show: true, radius: 13},
			 valueLabels: {
			 	show: true,
			 	yoffset: 23,
			 	fontcolor: '#2C2C2C',
			 	font: "11pt Roboto", // <=========================== My custom font
			 },
		}
	];

var options = {

	series: { curvedLines: {active: true} },

	yaxis: { show: false },

	grid: {
	 	margin: 15,
	}
};

$(document).ready(function () {
	$.plot($("#grafica"), dataset, options);
});
```

This is my CSS:
```CSS
@font-face {
    font-family: 'Roboto';
    src: url('../fuentes/Roboto-Regular.eot');
    src: url('../fuentes/Roboto-Regular.eot?#iefix') format('embedded-opentype'),
        url('../fuentes/Roboto-Regular.woff2') format('woff2'),
        url('../fuentes/Roboto-Regular.woff') format('woff'),
        url('../fuentes/Roboto-Regular.ttf') format('truetype'),
        url('../fuentes/Roboto-Regular.svg#Roboto-Regular') format('svg');
    font-weight: normal;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'Roboto-bold';
    src: url('../fuentes/Roboto-Bold.eot');
    src: url('../fuentes/Roboto-Bold.eot?#iefix') format('embedded-opentype'),
        url('../fuentes/Roboto-Bold.woff2') format('woff2'),
        url('../fuentes/Roboto-Bold.woff') format('woff'),
        url('../fuentes/Roboto-Bold.ttf') format('truetype'),
        url('../fuentes/Roboto-Bold.svg#Roboto-Bold') format('svg');
    font-weight: normal;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'Roboto-black';
    src: url('../fuentes/Roboto-Black.eot');
    src: url('../fuentes/Roboto-Black.eot?#iefix') format('embedded-opentype'),
        url('../fuentes/Roboto-Black.woff2') format('woff2'),
        url('../fuentes/Roboto-Black.woff') format('woff'),
        url('../fuentes/Roboto-Black.ttf') format('truetype'),
        url('../fuentes/Roboto-Black.svg#Roboto-Black') format('svg');
    font-weight: normal;
    font-style: normal;
    font-display: swap;
}

* { font-family: Roboto, sans-serif; }
```
